project_id = "dzxkvzdwapaoeewqiyyq"

[functions.create-guard]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = false

[functions.bulk-delete-reports]
verify_jwt = false

[functions.reset-company-admin-password]
verify_jwt = false