// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxetlcrxiqbpybzhpfwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4ZXRsY3J4aXFicHliemhwZndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NzE3MjksImV4cCI6MjA3OTE0NzcyOX0.v8HRUcCXjuSVhAiF5HRDqN2phAj36-JZf_cx6Mol9fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});