// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzxkvzdwapaoeewqiyyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6eGt2emR3YXBhb2Vld3FpeXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODQ4NzEsImV4cCI6MjA2ODI2MDg3MX0.XKltBt2-C5YA4YXmQS9aOY9O1gc1EHyEj4Aht2KjdDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});